spring.application.name=crash-detection-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/crash_detection_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# for configuration of Hibernate for PostGIS
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect